export const AVATARS = [
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_1.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_2.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_3.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_4.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_5.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_6.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_7.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_8.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_9.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_10.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_11.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_12.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_13.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_14.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_15.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_16.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_17.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_18.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_19.png",
  "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_20.png",
] as const;